-- 코드를 입력하세요
SELECT author.AUTHOR_ID, author.AUTHOR_NAME, book.CATEGORY, SUM(sales.SALES * book.PRICE) AS TOTAL_SALES
FROM BOOK_SALES sales
LEFT JOIN BOOK book ON sales.BOOK_ID = book.BOOK_ID
LEFT JOIN AUTHOR author ON book.AUTHOR_ID = author.AUTHOR_ID
WHERE sales.SALES_DATE BETWEEN '2022-01-01' AND '2022-01-31'
GROUP BY author.AUTHOR_ID, book.CATEGORY
ORDER BY author.AUTHOR_ID ASC, book.CATEGORY DESC;