-- 코드를 입력하세요
# SELECT u.USER_ID, u.NICKNAME, CONCAT(u.CITY, " ", u.STREET_ADDRESS1, u.STREET_ADDRESS2) AS 전체주소, 
# CONCAT(SUBSTR(TLNO, 1, 3), '-', SUBSTR(TLNO, 4, 4), '-', SUBSTR(TLNO, 8, 4)) AS 전화번호
# FROM USED_GOODS_USER u
# WHERE u.USER_ID IN (SELECT WRITER_ID FROM USED_GOODS_BOARD GROUP BY WRITER_ID HAVING COUNT(*) >= 3)
# ORDER BY u.USER_ID DESC;

SELECT 
    u.USER_ID, 
    u.NICKNAME, 
    CONCAT(u.CITY, ' ', u.STREET_ADDRESS1, ' ', IFNULL(u.STREET_ADDRESS2, '')) AS 전체주소, 
    CONCAT(SUBSTR(u.TLNO, 1, 3), '-', SUBSTR(u.TLNO, 4, 4), '-', SUBSTR(u.TLNO, 8, 4)) AS 전화번호
FROM 
    USED_GOODS_USER u
WHERE 
    u.USER_ID IN (SELECT WRITER_ID FROM USED_GOODS_BOARD GROUP BY WRITER_ID HAVING COUNT(*) >= 3)
ORDER BY 
    u.USER_ID DESC;
