-- 코드를 입력하세요
WITH RENTED AS (
    SELECT DISTINCT history.CAR_ID
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY history
    WHERE history.START_DATE <= '2022-10-16' AND history.END_DATE >= '2022-10-16'
)

SELECT 
    id.CAR_ID AS CAR_ID, 
    CASE WHEN id.CAR_ID IN (SELECT CAR_ID FROM RENTED) THEN '대여중' ELSE '대여 가능' END AS AVAILABILITY
FROM (SELECT DISTINCT CAR_ID FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY) as id
ORDER BY id.CAR_ID DESC;



