SELECT 
    H.HISTORY_ID,
    CASE 
        WHEN DATEDIFF(H.END_DATE, H.START_DATE) + 1 < 7 THEN ROUND(C.DAILY_FEE * (DATEDIFF(H.END_DATE, H.START_DATE) + 1))
        WHEN DATEDIFF(H.END_DATE, H.START_DATE) + 1 < 30 THEN ROUND(C.DAILY_FEE * (DATEDIFF(H.END_DATE, H.START_DATE) + 1) * (1 - P1.DISCOUNT_RATE / 100.0))
        WHEN DATEDIFF(H.END_DATE, H.START_DATE) + 1 < 90 THEN ROUND(C.DAILY_FEE * (DATEDIFF(H.END_DATE, H.START_DATE) + 1) * (1 - P2.DISCOUNT_RATE / 100.0))
        ELSE ROUND(C.DAILY_FEE * (DATEDIFF(H.END_DATE, H.START_DATE) + 1) * (1 - P3.DISCOUNT_RATE / 100.0))
    END AS FEE
FROM 
    CAR_RENTAL_COMPANY_CAR C
JOIN 
    CAR_RENTAL_COMPANY_RENTAL_HISTORY H ON C.CAR_ID = H.CAR_ID
LEFT JOIN 
    CAR_RENTAL_COMPANY_DISCOUNT_PLAN P1 ON C.CAR_TYPE = P1.CAR_TYPE AND P1.DURATION_TYPE = '7일 이상'
LEFT JOIN 
    CAR_RENTAL_COMPANY_DISCOUNT_PLAN P2 ON C.CAR_TYPE = P2.CAR_TYPE AND P2.DURATION_TYPE = '30일 이상'
LEFT JOIN 
    CAR_RENTAL_COMPANY_DISCOUNT_PLAN P3 ON C.CAR_TYPE = P3.CAR_TYPE AND P3.DURATION_TYPE = '90일 이상'
WHERE 
    C.CAR_TYPE = '트럭'
ORDER BY 
    FEE DESC, H.HISTORY_ID DESC;
