SELECT july.FLAVOR
FROM JULY july
LEFT JOIN FIRST_HALF half ON july.FLAVOR = half.FLAVOR
GROUP BY july.FLAVOR, half.TOTAL_ORDER
ORDER BY COALESCE(half.TOTAL_ORDER, 0) + SUM(july.TOTAL_ORDER) DESC
LIMIT 3;
